### ISSUE TITLE
New F-Droid release?

### ISSUE THREAD

**Issue by rusty-snake** [opendocument-app/OpenDocument.droid#328]
F-Droid is still at 'Version 3.19 (172) (2022-03-04)' while Google Play is at '3.24 (20.08.2023)' or so.

Also what do you think about attaching apks to the release (here at GitHub) so users ob Obtainium can install it that way?

**Comment by TomTasche** [comment]
The process to publish on F-Droid was painfully complicated last time I checked... It's not worth it for me, but I'm happy if someone would like to do that for us.

Never heard of Obtainium - sounds interesting! I'll do that from now on. Thanks for the tip!

**Comment by rusty-snake** [comment]
> The process to publish on F-Droid was painfully complicated last time I checked

Agree. That's why there are slow updates and I try to avoid it by using Obtainium for example.

>  I'll do that from now on.

Greate, Thanks.

**Comment by licaon-kter** [comment]
> The process to publish on F-Droid was painfully complicated last time I checked... 

It's as easy as the build procedure of the app... if the app is FOSS and has FOSS dependencies everything is simple...

The current recipe for this app is unfortunately a big web of cleaning commands and of old dependencies versions pins 

That aside, trying to update it now... it fails for `conan`
```
  - versionName: '3.24'
    versionCode: 177
    commit: f33ded86b3bb0bd4e62c9aead37063a087180043
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y cmake ninja-build python3-pip
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
      - pip3 install wheel
      - pip3 install conan
    gradle:
      - pro
    prebuild:
      - sed -i -e '/com.google/d' ../build.gradle
      - sed -i -e '/com.google.firebase/d' -e '/firebaseCrashlytics/d' -e '/com.google.android.play/d'
        -e '/com.android.billingclient/d' -e '/com.google.gms/d' -e '/pro"/d' -e '/com.google.android.gms/d'
        build.gradle
      - sed -i -e '/INTERNET/d' -e '/BILLING/d' -e '/^        <meta-data/,+5d' src/main/AndroidManifest.xml
      - cd src/main/java/at/tomtasche/reader
      - sed -i -e '/com.google.firebase/d' background/FileLoader.java
      - sed -i -e '/gms/d' -e '/play.core/d' -e '/firebase/d' ui/activity/*.java
      - sed -i -e '/private Uri doFirebaseConvert/,/^    }/d' -e 's/viewerUri = doFirebaseConvert(options)/return/'
        -e '/com.google/d' -e '/Firebase/d' -e '/Storage/d' -e '/auth /d' -e '/storage
        /d' background/OnlineLoader.java
      - sed -i -e '/void initializeProprietaryLibraries/,/^    }/d' -e '/initializeProprietaryLibraries/d'
        -e '/void buyAdRemoval/,/^    }/d' -e '/buyAdRemoval/d' -e 's/billingManager.hasPurchased()/true/'
        -e 's/billingManager.isEnabled()/false/' -e '/addOnPreDrawListener/,/});/d'
        ui/activity/MainActivity.java
      - sed -i -e '/getBooleanConfig("show_in_app_rating/,/^                });/d'
        -e '/void offerUpload/,/^    }/d' -e '/offerUpload/d' -e '/void requestInAppRating/,/^    }/d'
        -e '/requestInAppRating/d' ui/activity/DocumentFragment.java
      - sed -i -e 's/configManager.getBooleanConfig(".*")/null/' background/OdfLoader.java
      - for class in AdManager AnalyticsManager BillingManager ConfigManager CrashManager
        HelpManager; do echo "package at.tomtasche.reader.nonfree; public class ${class}
        {}" > nonfree/${class}.java; sed -i -e "/${class}\./Id" background/*.java
        ui/*/*.java ui/*.java; done
      - conan config set general.revisions_enabled=1
      - conan remote add odr https://odr.jfrog.io/artifactory/api/conan/odr-conan
    ndk: 25.2.9519653
```

fails because that odr URL is no longer valid and spits out HTML.

If I don't pin `conan` version `config set` is invalid

If I remove both `conan` lines it fails later for another reason.

The CI workflow I guess is never used, since we're mirroring the same commands that fail.
